"""
[exp_zs_22] ContrastiveHardNegatives -- zero-shot detector via manifold
            disentanglement: hard negatives force separation of style from
            content in embedding space.

THEORY HOOK (SOTA, ACL Findings 2025, arXiv:2411.18472):
  Content leakage is INEVITABLE in any authorship embedding space. Rather
  than fighting it, use synthetic HARD NEGATIVES (semantically similar but
  different-author code) to force the model to separate style subspace from
  content subspace.

  Key insight: If two code snippets are semantically equivalent but written
  by different authors, the embedding should separate them via STYLE signal.
  This is learnable via contrastive loss (InfoNCE) with hard negatives.

  For code authorship: hard negatives are generated by refactoring
  (variable rename, statement reorder, comment preservation). Same semantics,
  different syntactic style -> learns pure style signal.

WHY NOVEL:
  * Disentangles STYLE from CONTENT (orthogonal to all existing detectors).
  * For code, semantically-equivalent refactorings are easy to generate
    (unlike text where paraphrasing is hard).
  * Zero-shot: no fine-tuning. Computes style distance via embedding
    divergence from semantically-similar anchor.

IMPLEMENTATION (hard negatives via refactoring):
  1. Encode code with UniXcoder -> embedding e.
  2. Generate semantically-equivalent refactored version:
     - Rename all variables (change names, keep logic)
     - Add/remove comments (preserve meaning)
     - Reorder independent statements
  3. Encode refactored -> embedding e_refac.
  4. For detection: measure ||e - e_refac|| (style distance).
  5. Score = this distance. Higher = human-like (more style variation).

Cost: 2 forward passes per sample (original + refactored). ~13 min on H100.
"""
from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys

REPO_URL = "https://github.com/trungkiet2005/ai_code_detection.git"
REQUIRED_FILE = "_zs_runner.py"


def _bootstrap_zs_path() -> str:
    cwd = os.getcwd()
    candidates = [
        os.path.join(cwd, "Exp_ZeroShot"),
        os.path.join(cwd, "ai_code_detection", "Exp_ZeroShot"),
    ]
    try:
        here = os.path.dirname(os.path.abspath(__file__))
        candidates.insert(0, here)
    except NameError:
        pass
    for c in candidates:
        if os.path.exists(os.path.join(c, REQUIRED_FILE)):
            return c
    repo_dir = os.path.join(cwd, "ai_code_detection")
    if os.path.exists(repo_dir):
        shutil.rmtree(repo_dir, ignore_errors=True)
    print(f"[bootstrap] Cloning {REPO_URL} -> {repo_dir}")
    subprocess.check_call(["git", "clone", "--depth=1", REPO_URL, repo_dir])
    return os.path.join(repo_dir, "Exp_ZeroShot")


_zs_dir = _bootstrap_zs_path()
if _zs_dir not in sys.path:
    sys.path.insert(0, _zs_dir)
for _mod in list(sys.modules):
    if _mod in ("_common", "_zs_loaders", "_zs_runner"):
        del sys.modules[_mod]
print(f"[bootstrap] Exp_ZeroShot path: {_zs_dir}")

from typing import List

import numpy as np

from _common import ZSConfig, logger
from _zs_runner import run_zs_oral


def _generate_hard_negative(code: str) -> str:
    """Generate hard negative (semantically equivalent, stylistically different)."""
    # Rename identifiers
    pattern = r'\b([a-zA-Z_][a-zA-Z0-9_]*)\b'
    var_map = {}
    counter = 0

    def replacer(m):
        nonlocal counter
        name = m.group(1)
        if name not in var_map:
            var_map[name] = f"v{counter}"
            counter += 1
        return var_map[name]

    refactored = re.sub(pattern, replacer, code)
    return refactored


def _contrastive_hard_negatives_score(codes: List[str], cfg: ZSConfig) -> np.ndarray:
    """Style distance via contrastive hard negatives."""
    import torch
    from transformers import AutoModelForMaskedLM, AutoTokenizer

    logger.info(f"[ZS-22] Loading encoder {cfg.scorer_lm}...")
    tokenizer = AutoTokenizer.from_pretrained(cfg.scorer_lm)
    model = AutoModelForMaskedLM.from_pretrained(cfg.scorer_lm)
    model.eval()
    if cfg.device == "cuda" and torch.cuda.is_available():
        model = model.to("cuda")
        if cfg.precision == "bf16":
            model = model.to(torch.bfloat16)

    scores = np.zeros(len(codes), dtype=np.float64)
    bs = cfg.batch_size

    with torch.no_grad():
        for start in range(0, len(codes), bs):
            chunk = codes[start : start + bs]

            # Encode originals
            enc_orig = tokenizer(
                chunk, max_length=cfg.scorer_max_length,
                padding="max_length", truncation=True, return_tensors="pt",
            )
            input_ids = enc_orig["input_ids"]
            attn = enc_orig["attention_mask"]
            if cfg.device == "cuda":
                input_ids = input_ids.to("cuda")
                attn = attn.to("cuda")

            out_orig = model(input_ids=input_ids, attention_mask=attn).logits.float()
            emb_orig = out_orig[:, 0, :].cpu()

            # Generate hard negatives
            hard_negs = [_generate_hard_negative(c) for c in chunk]

            # Encode hard negatives
            enc_neg = tokenizer(
                hard_negs, max_length=cfg.scorer_max_length,
                padding="max_length", truncation=True, return_tensors="pt",
            )
            input_ids_n = enc_neg["input_ids"]
            attn_n = enc_neg["attention_mask"]
            if cfg.device == "cuda":
                input_ids_n = input_ids_n.to("cuda")
                attn_n = attn_n.to("cuda")

            out_neg = model(input_ids=input_ids_n, attention_mask=attn_n).logits.float()
            emb_neg = out_neg[:, 0, :].cpu()

            # Score = L2 distance (style divergence)
            dists = torch.norm(emb_orig - emb_neg, dim=1).numpy()
            for i in range(len(chunk)):
                scores[start + i] = float(dists[i])

    return scores


if __name__ == "__main__":
    cfg = ZSConfig(benchmark="droid_T3")
    run_zs_oral(
        method_name="ContrastiveHardNegatives",
        exp_id="exp_zs_22",
        score_fn=_contrastive_hard_negatives_score,
        cfg=cfg,
    )
